# Generated by Django 4.0.2 on 2022-02-22 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue_service', '0002_alter_issue_answerfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issueDoc',
            field=models.FileField(blank=True, default='', upload_to='static'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
