# Generated by Django 4.0.2 on 2022-02-18 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_service', '0002_alter_issue_answerfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 14, 38, 54, 581833)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issueDoc',
            field=models.FileField(blank=True, default='', upload_to='static'),
        ),
    ]
