# Generated by Django 4.0.2 on 2022-02-18 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_service', '0003_issue_end_date_alter_issue_issuedoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 14, 51, 59, 170564)),
        ),
    ]
