# Generated by Django 4.0.2 on 2022-02-22 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('issue_service', '0003_alter_issue_issuedoc_alter_issue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='end_date',
            field=models.TimeField(default=datetime.datetime(2022, 2, 22, 12, 31, 51, 684758, tzinfo=utc)),
        ),
    ]
