# Generated by Django 4.0.2 on 2022-02-22 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('issue_service', '0004_issue_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='user',
        ),
        migrations.AlterField(
            model_name='issue',
            name='end_date',
            field=models.TimeField(default=datetime.datetime(2022, 2, 22, 12, 33, 58, 775799, tzinfo=utc)),
        ),
    ]
