# Generated by Django 4.0.2 on 2022-02-22 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_service', '0006_issue_user_alter_issue_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
