# Generated by Django 4.0.2 on 2022-02-23 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_service', '0007_alter_issue_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
