# Generated by Django 4.0.2 on 2022-02-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_service', '0008_alter_issue_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
