# Generated by Django 4.0.2 on 2022-02-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='type',
            field=models.CharField(default='undefined', max_length=10),
        ),
    ]
