# Generated by Django 4.0.2 on 2022-02-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_service', '0002_storage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='name',
            field=models.CharField(default='undefined', max_length=30),
        ),
    ]
