# Generated by Django 4.0.2 on 2022-04-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_group_account_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.CharField(default='img/undraw_profile.svg', max_length=255),
        ),
    ]
