# Generated by Django 4.0.2 on 2022-02-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_alter_teams_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='user',
        ),
    ]
