# Generated by Django 4.0.2 on 2022-04-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0004_alter_account_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.CharField(default='static/img/undraw_profile.svg', max_length=255),
        ),
    ]
