# Generated by Django 4.0.2 on 2022-02-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
