# Generated by Django 4.0.2 on 2022-02-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0007_alter_userprofile_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
