# Generated by Django 4.0.2 on 2022-02-11 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_service', '0007_alter_schedule_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='calendar_service.lesson'),
        ),
    ]
