# Generated by Django 4.0.2 on 2022-02-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_service', '0010_alter_schedule_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='order',
            field=models.IntegerField(choices=[('08:00 - 09:30', '08:00 - 09:30'), ('09:45 - 11:15', '09:45 - 11:15'), ('11:30 - 13:00', '11:30 - 13:00'), ('13:30 - 15:00', '13:30 - 15:00'), ('15:15 - 16:45', '15:15 - 16:45'), ('17:00 - 18:30', '17:00 - 18:30')]),
        ),
    ]
