# Generated by Django 4.0.2 on 2022-02-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_service', '0012_remove_schedule_order_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
