# Generated by Django 4.0.2 on 2022-02-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_service', '0015_remove_schedule_meet_link_lesson_meet_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='lesson_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_service.lesson'),
        ),
    ]
