# Generated by Django 4.0.2 on 2022-02-16 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar_service', '0016_alter_issue_lesson_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.AddField(
            model_name='issue',
            name='issue',
            field=models.TextField(default='Issue description'),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(default='Issue', max_length=70),
        ),
        migrations.AddField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
