# Generated by Django 4.0.2 on 2022-02-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_service', '0017_rename_lesson_id_issue_lesson_issue_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issueDoc',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
