# Generated by Django 4.0.2 on 2022-02-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_service', '0018_issue_issuedoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issueDoc',
            field=models.FileField(default='', upload_to='static'),
        ),
    ]
