# Generated by Django 4.0.2 on 2022-02-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_service', '0019_alter_issue_issuedoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='answerFile',
            field=models.FileField(default='', upload_to='static'),
        ),
    ]
