# Generated by Django 4.0.2 on 2022-02-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_service', '0020_issue_answerfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
