# Generated by Django 4.0.2 on 2022-02-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
        ('calendar_service', '0021_delete_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_service.teams'),
        ),
    ]
